# -*- coding: utf-8 -*-
"""data-parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJIuS-65uRoadJQwz3sUTzjPiXj66o_x
"""

import pandas as pd
import re

df = pd.read_csv('/content/challenge_data-v1.csv')
display(df.head())

#total cells
print(len(df))

# This code prints the data types of all columns in the DataFrame 'df'
print(df.dtypes)

# This code prints the distinct values in the 'manufacturer' column
distinct_manufacturers = df['manufacturer'].unique()
print("Distinct Manufacturers:", distinct_manufacturers)

# This code prints the total count of distinct manufacturers
total_distinct_manufacturers = df['manufacturer'].nunique()
print("\nTotal count of distinct manufacturers:", total_distinct_manufacturers)

# This code groups the DataFrame by 'manufacturer' and counts the number of unique models for each manufacturer
models_per_manufacturer = df.groupby('manufacturer')['model'].nunique()
print("Number of unique models per manufacturer:\n", models_per_manufacturer)

# This code filters the DataFrame for 'PHILIPS' and 'Philips' manufacturers and prints their distinct models
philips_models = df[df['manufacturer'].isin(['PHILIPS', 'Philips'])]['model'].unique()
print("Distinct models for PHILIPS and Philips:", philips_models)

def decode_linet(serial):
    s = serial.strip()

    match = re.match(r'^(20\d{2})', s)
    if match:
        return match.group(1)

    return None

def decode_stryker(serial):
    s = serial.strip()

    # standard: starts with full YYYY
    match = re.match(r'^(20\d{2})', s)
    if match:
        return match.group(1)

    # fallback: 2-digit year at start (e.g. 109035466 → 10 → 2010)
    match2 = re.match(r'^(\d{2})\d', s)
    if match2:
        yy = int(match2.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)

    return None

def decode_edan(serial):
    s = re.sub(r'^\(21\)', '', serial.strip()).strip()

    # find M or K followed by exactly 2 digits
    match = re.search(r'[MK](\d{2})', s)
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:  # sanity check
            return str(2000 + yy)

    return None

def decode_hillrom(serial):
    s = serial.strip()

    # CENTURY, CENTURYP1400, PCENTURYK3256 — year is last 4 digits
    match = re.search(r'(19\d{2}|20\d{2})$', s)
    if match:
        return match.group(1)

    # P3200 — [Letter][YY] at start
    match2 = re.match(r'^[A-Z](\d{2})', s)
    if match2:
        return str(2000 + int(match2.group(1)))

    return None

def decode_zoll(serial):
    MONTH_MAP = {
        'A': 'January', 'B': 'February', 'C': 'March', 'D': 'April',
        'E': 'May', 'F': 'June', 'G': 'July', 'H': 'August',
        'I': 'September', 'J': 'October', 'K': 'November', 'L': 'December'
    }

    cleaned = re.sub(r'^\(21\)\s*', '', serial.strip()).upper()
    cleaned = re.sub(r'^\d([A-Z])', r'\1', cleaned)

    # standard: [1-2 letter product code][2-digit year][month letter]
    match = re.match(r'^([A-Z]{1,2})(\d{2})([A-Z])', cleaned)
    if match:
        month_char = match.group(3)
        if month_char in MONTH_MAP:
            year = 2000 + int(match.group(2))
            month = MONTH_MAP[month_char]
            return f"{month} {year}"

    # fallback: single digit year (e.g. t1k → T1K → 2001)
    match2 = re.match(r'^([A-Z]{1,2})(\d)([A-Z])', cleaned)
    if match2:
        month_char = match2.group(3)
        if month_char in MONTH_MAP:
            year = 2000 + int(match2.group(2))
            month = MONTH_MAP[month_char]
            return f"{month} {year}"

    return None

def decode_arjo(serial):
    s = serial.strip()

    match = re.match(r'^(\d{2})', s)
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)

    return None

def decode_biosonic(serial):
    match = re.match(r'^(\d{2})', serial.strip())
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_covidien(serial):
    match = re.match(r'^VL0(\d{2})', serial.strip())
    if match:
        return str(2000 + int(match.group(1)))
    return None

def decode_labcorp(serial):
    match = re.match(r'^(\d{2})', serial.strip())
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_unico(serial):
    match = re.search(r'(20\d{2})\d{4}', serial.strip())
    if match:
        return match.group(1)
    return None

def decode_jiangmen(serial):
    match = re.search(r'(20\d{2})', serial.strip())
    if match:
        return match.group(1)
    return None

def decode_american_diagnostic(serial):
    s = serial.strip().lstrip('C')
    match = re.match(r'^(\d{2})', s)
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_cogentix(serial):
    match = re.match(r'^CS(\d{2})', serial.strip())
    if match:
        return str(2000 + int(match.group(1)))
    return None

def decode_exergen(serial):
    match = re.match(r'^A(\d{2})', serial.strip())
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_masimo(serial):
    match = re.match(r'^M(\d{2})', serial.strip())
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_thermo(serial):
    match = re.match(r'^(\d{2})', serial.strip())
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_ge(serial):
    s = serial.strip()

    # SA3YY pattern (e.g. SA315219009 → 2015)
    match = re.match(r'^SA3(\d{2})', s)
    if match:
        return str(2000 + int(match.group(1)))

    # SPX YY pattern (e.g. SPX18510114SA → 2018)
    match = re.match(r'^SPX(\d{2})', s)
    if match:
        return str(2000 + int(match.group(1)))

    # RTS YY pattern (e.g. RTS14024388GA → 2014)
    match = re.match(r'^RTS(\d{2})', s)
    if match:
        return str(2000 + int(match.group(1)))

    # RT9YY pattern (e.g. RT916162191SA → 2016, RT908362478GA → 2008)
    match = re.match(r'^RT9(\d{2})', s)
    if match:
        return str(2000 + int(match.group(1)))

    return None

def decode_hospira(serial):
    s = serial.strip()
    match = re.match(r'^(\d{2})', s)
    if match:
        yy = int(match.group(1))
        if 0 <= yy <= 30:
            return str(2000 + yy)
    return None

def decode_olympus(serial):
    s = serial.strip()
    match = re.match(r'^(\d+)', s)
    if match:
        return None  # no year pattern found, update when researched
    return None

def decode_welch_allyn(serial, model):
    s = serial.strip()
    
    if model == 'FILAC3000':
        core = re.sub(r'^A', '', s)
        match = re.match(r'^(\d{2})', core)
        if match:
            yy = int(match.group(1))
            if 0 <= yy <= 30:
                return str(2000 + yy)
    
    elif model == 'SPOT VITAL SIGNS':
        match = re.match(r'^(20\d{2})', s)
        if match:
            return match.group(1)
    
    elif model == 'SURETEMPPLUS':
        pass  # needs research
    
    return None

def decode_baxter(serial):
    return None

def decode_mindray(serial):
    return None

def decode_manufacturing_year(manufacturer, model, serial):
    """
    Returns the manufacturing year (int) for a given device record.
    Returns None if unable to determine.
    """
    s = serial.strip()
    m = manufacturer.strip()

    # ── ZOLL Medical ─────────────────────────────────────────────────
    if m == 'ZOLL Medical':
        dzoll_answer = decode_zoll(s)
        if dzoll_answer:
            return dzoll_answer

    # ── Add more manufacturers below as you crack them ────────────────
    if m == 'Hillrom':
        dhillrom_answer = decode_hillrom(s)
        if dhillrom_answer:
            return dhillrom_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Stryker':
        dstryker_answer = decode_stryker(s)
        if dstryker_answer:
            return dstryker_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'LINET':
        dlinet_answer = decode_linet(s)
        if dlinet_answer:
            return dlinet_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Edan Instruments':
        dedan_answer = decode_edan(s)
        if dedan_answer:
            return dedan_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'ARJO INC.':
        darjo_answer = decode_arjo(s)
        if darjo_answer:
            return darjo_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'BIOSONIC':
        dbiosonic_answer = decode_biosonic(s)
        if dbiosonic_answer:
            return dbiosonic_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Covidien':
        dcovidien_answer = decode_covidien(s)
        if dcovidien_answer:
            return dcovidien_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'LAB CORP.':
        dlabcorp_answer = decode_labcorp(s)
        if dlabcorp_answer:
            return dlabcorp_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Unico':
        dunico_answer = decode_unico(s)
        if dunico_answer:
            return dunico_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Jiangmen Dacheng Medical Equipment Co.':
        djiemen_answer = decode_jiangmen(s)
        if djiemen_answer:
            return djiemen_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'American Diagnostic':
        damdiagnostic_answer = decode_american_diagnostic(s)
        if damdiagnostic_answer:
            return damdiagnostic_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Cogentix Medical':
        dcogentix_answer = decode_cogentix(s)
        if dcogentix_answer:
            return dcogentix_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Exergen':
        dexergen_answer = decode_exergen(s)
        if dexergen_answer:
            return dexergen_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Masimo':
        dmasimo_answer = decode_masimo(s)
        if dmasimo_answer:
            return dmasimo_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'THERMO SCIENTIFIC':
        dthermo_answer = decode_thermo(s)
        if dthermo_answer:
            return dthermo_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'GE HEALTHCARE':
        dge_answer = decode_ge(s)
        if dge_answer:
            return dge_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Hospira':
        dhospira_answer = decode_hospira(s)
        if dhospira_answer:
            return dhospira_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Olympus':
        dolympus_answer = decode_olympus(s)
        if dolympus_answer:
            return dolympus_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Welch Allyn':
        dwelchallyn_answer = decode_welch_allyn(s, model)
        if dwelchallyn_answer:
            return dwelchallyn_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'BAXTER HEALTHCARE CORP.':
        dbaxter_answer = decode_baxter(s)
        if dbaxter_answer:
            return dbaxter_answer
    # ──────────────────────────────────────────────────────────────────
    if m == 'Mindray':
        dmindray_answer = decode_mindray(s)
        if dmindray_answer:
            return dmindray_answer
    # ──────────────────────────────────────────────────────────────────

    return None

# This function applies the 'decode_manufacturing_year' function to each row of the DataFrame
def add_manufacturing_year(dataframe):
    dataframe['manufacturing_year'] = dataframe.apply(
        lambda row: decode_manufacturing_year(row['manufacturer'], row['model'], row['serial number']),
        axis=1
    )
    return dataframe

# Apply the function to your DataFrame
df = add_manufacturing_year(df)

# Display data for 'Hillrom' manufacturer with the new 'manufacturing_year' column
hillrom_df = df[df['manufacturer'].isin(['GE HEALTHCARE'])]
display(hillrom_df)

# This code saves the DataFrame 'df' to a new CSV file named 'challenge_data_with_year.csv' without the index
df.to_csv('challenge_data_with_year.csv', index=False)
print("DataFrame saved to challenge_data_with_year.csv")

df[df['manufacturer'] == 'GE HEALTHCARE']['serial number'].str[:4].unique()